name: Build Backend CI

on:
  push:
    branches: [ master ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd backend && \
        docker build . --file Dockerfile \
        --tag ft-backend:$(date +%s) \
        --tag ft-backend:latest
